export const timezones = [
	{
		abbreviation: "ACDT",
		full_name: "Australian Central Daylight Time",
		code: "UTC+10:30",
	},
	{
		abbreviation: "ACST",
		full_name: "Australian Central Standard Time",
		code: "UTC+09:30",
	},
	{ abbreviation: "ACT", full_name: "Acre Time", code: "UTC-05:00" },
	{
		abbreviation: "ADT",
		full_name: "Atlantic Daylight Time",
		code: "UTC-03:00",
	},
	{
		abbreviation: "AEDT",
		full_name: "Australian Eastern Daylight Time",
		code: "UTC+11:00",
	},
	{
		abbreviation: "AEST",
		full_name: "Australian Eastern Standard Time",
		code: "UTC+10:00",
	},
	{ abbreviation: "AFT", full_name: "Afghanistan Time", code: "UTC+04:30" },
	{
		abbreviation: "AKDT",
		full_name: "Alaska Daylight Time",
		code: "UTC-08:00",
	},
	{
		abbreviation: "AKST",
		full_name: "Alaska Standard Time",
		code: "UTC-09:00",
	},
	{ abbreviation: "ALMT", full_name: "Alma-Ata Time", code: "UTC+06:00" },
	{ abbreviation: "AMT", full_name: "Amazon Time", code: "UTC-04:00" },
	{ abbreviation: "ART", full_name: "Argentina Time", code: "UTC-03:00" },
	{
		abbreviation: "AST",
		full_name: "Atlantic Standard Time",
		code: "UTC-04:00",
	},
	{
		abbreviation: "AWST",
		full_name: "Australian Western Standard Time",
		code: "UTC+08:00",
	},
	{ abbreviation: "AZOST", full_name: "Azores Summer Time", code: "UTC+00:00" },
	{ abbreviation: "AZT", full_name: "Azerbaijan Time", code: "UTC+04:00" },
	{
		abbreviation: "BDT",
		full_name: "Bangladesh Standard Time",
		code: "UTC+06:00",
	},
	{
		abbreviation: "BIOT",
		full_name: "British Indian Ocean Time",
		code: "UTC+06:00",
	},
	{ abbreviation: "BIT", full_name: "Baker Island Time", code: "UTC-12:00" },
	{ abbreviation: "BOT", full_name: "Bolivia Time", code: "UTC-04:00" },
	{
		abbreviation: "BRST",
		full_name: "Brasilia Summer Time",
		code: "UTC-02:00",
	},
	{ abbreviation: "BRT", full_name: "Brasilia Time", code: "UTC-03:00" },
	{ abbreviation: "BST", full_name: "British Summer Time", code: "UTC+01:00" },
	{ abbreviation: "BTT", full_name: "Bhutan Time", code: "UTC+06:00" },
	{ abbreviation: "CAT", full_name: "Central Africa Time", code: "UTC+02:00" },
	{
		abbreviation: "CET",
		full_name: "Central European Time",
		code: "UTC+01:00",
	},
	{
		abbreviation: "CEST",
		full_name: "Central European Summer Time",
		code: "UTC+02:00",
	},
	{
		abbreviation: "CHST",
		full_name: "Chamorro Standard Time",
		code: "UTC+10:00",
	},
	{
		abbreviation: "CST",
		full_name: "Central Standard Time",
		code: "UTC-06:00",
	},
	{ abbreviation: "CT", full_name: "China Time", code: "UTC+08:00" },
	{ abbreviation: "CVT", full_name: "Cape Verde Time", code: "UTC-01:00" },
	{
		abbreviation: "EDT",
		full_name: "Eastern Daylight Time",
		code: "UTC-04:00",
	},
	{
		abbreviation: "EET",
		full_name: "Eastern European Time",
		code: "UTC+02:00",
	},
	{
		abbreviation: "EEST",
		full_name: "Eastern European Summer Time",
		code: "UTC+03:00",
	},
	{
		abbreviation: "EST",
		full_name: "Eastern Standard Time",
		code: "UTC-05:00",
	},
	{ abbreviation: "FJT", full_name: "Fiji Time", code: "UTC+12:00" },
	{ abbreviation: "GMT", full_name: "Greenwich Mean Time", code: "UTC+00:00" },
	{ abbreviation: "HKT", full_name: "Hong Kong Time", code: "UTC+08:00" },
	{ abbreviation: "IST", full_name: "India Standard Time", code: "UTC+05:30" },
	{ abbreviation: "JST", full_name: "Japan Standard Time", code: "UTC+09:00" },
	{ abbreviation: "KST", full_name: "Korea Standard Time", code: "UTC+09:00" },
	{
		abbreviation: "MDT",
		full_name: "Mountain Daylight Time",
		code: "UTC-06:00",
	},
	{
		abbreviation: "MST",
		full_name: "Mountain Standard Time",
		code: "UTC-07:00",
	},
	{
		abbreviation: "PDT",
		full_name: "Pacific Daylight Time",
		code: "UTC-07:00",
	},
	{
		abbreviation: "PST",
		full_name: "Pacific Standard Time",
		code: "UTC-08:00",
	},
	{ abbreviation: "SGT", full_name: "Singapore Time", code: "UTC+08:00" },
	{
		abbreviation: "UTC",
		full_name: "Coordinated Universal Time",
		code: "UTC+00:00",
	},
	{ abbreviation: "WAT", full_name: "West Africa Time", code: "UTC+01:00" },
	{
		abbreviation: "WET",
		full_name: "Western European Time",
		code: "UTC+00:00",
	},
];
